"""changed user field is_active, default value to false.

Revision ID: 8a973752383b
Revises: 82efbfe6d48e
Create Date: 2023-04-11 12:21:49.097366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a973752383b'
down_revision = '82efbfe6d48e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
